plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace 'com.transfer.googleadmobnextgensdk'
    compileSdk 36

    defaultConfig {
        applicationId "com.transfer.googleadmobnextgensdk"
        minSdk 24
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {

        debug {

            minifyEnabled false

            resValue 'string', 'appid', '"ca-app-pub-3940256099942544~3347511713"'

            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

        }

        release {

            minifyEnabled false

            resValue 'string', 'appid', '"ca-app-pub-3940256099942544~3347511713"'

            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

        }

    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }

    buildFeatures {

        viewBinding true

    }
}

dependencies {
    implementation libs.androidx.activity.ktx
    implementation libs.androidx.appcompat
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.core.ktx
    implementation libs.core.ktx
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation libs.androidx.junit

    implementation project(':admobads')

    implementation("com.google.android.libraries.ads.mobile.sdk:ads-mobile-sdk:1.4.0")
}